### ISSUE TITLE
Controlar volume do bot em uma tela touchscreen

### ISSUE THREAD

**Issue by CaiqueTora** [JoaoPelizza/IRCTwitchBot#6]
Moço, quando faço stream ficou incomodado q tenho q ficar mexendo em uma telinha preta. Por favor fazer uma interface do controle do volume para meu smarthphone, q assim posso controlar o volume da stream quando estiver no ônibus. Desde já agradeço.

**Comment by jpelizza** [comment]
Já existe, faz parte do VLC, não tenho certeza se é integrado na biblioteca deles ou não, vou ver e respondo certinho se funciona direto ou não
